version: '3'

services:
  app:
    build:
      context: ./app
    working_dir: /opt/server
    env_file:
      - .env
    expose:
      - '3000'
    depends_on:
      - db
    volumes:
      - /opt/server/node_modules
    command: npm run start

  # Контейнер с базой данных
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      #- POSTGRES_DB=${DB_NAME}
    volumes:
      #- postgres:/var/lib/postgresql/data
      - ./db_data:/docker-entrypoint-initdb.d
    expose:
      - '5432'
    restart: always
    
  # Контейнер с nginx
  nginx:
    container_name: proxy_nginx
    depends_on:
      - app
      - db
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/var/www/static
    restart: always
  pgadmin:
    container_name: pgadmin
    depends_on:
      - db
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.ru
      PGADMIN_DEFAULT_PASSWORD: aaa000
    expose:
      - '80'
    restart: always

networks:
  network: {}